language: scala

scala:
  - "0.23.0-RC1"
  - "2.12.10"
  - "2.13.1"

jdk:
  - openjdk11

sudo: required
dist: trusty

env:
  - SCALAJS_VERSION=1.0.1
  - SCALAJS_VERSION=1.0.0-RC2

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.coursier
    - $HOME/.sbt

script:
  - if [[ "$TRAVIS_SCALA_VERSION" == 0.* ]];
    then
      sbt ++$TRAVIS_SCALA_VERSION coreJVM/test;
    else
      sbt ++$TRAVIS_SCALA_VERSION fmtCheck test mimaReportBinaryIssues;
    fi

